
[[ $- != *i* ]] && return

export PATH="$PATH:/home/marek/go/bin"

alias ls='exa --color=auto'
alias ll='exa --color=auto -l'
alias la='exa --color=auto -la'

alias cat='bat -p'
#alias sudo='doas'

alias x='sudo xbps-install -Suy'
alias strtup='sudo wpa_supplicant -B -c/etc/wpa_supplicant.conf -iwlp2s0; sudo dhcpcd wlp2s0; startx'

PS1='\033[32m\033[1m[ \W ]\$ \033[0m'
